import './globals.css'
import type { Metadata } from 'next'
import StateContext from '@/context/StateContext'
import { Montserrat } from 'next/font/google'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lista de lectura',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <StateContext>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </StateContext>
  )
}
